swagger: '2.0'

schemes: 
  - http
  - https

host: localhost:8085
basePath: /gestorencomendas-api/v1

info:
  version: 1.0.0
  title: Gestor de Encomendas Api
  description: Registo e acompanhamento de encomendas de produtos numa empresa
  termsOfService: http://localhost:8085/gestorencomendas-api/
  contact:
    name: SuporteAI3
    url: http://localhost:8085/gestorencomendas-api/v1/termo-uso
    email: estgv*****@alunos.estgv.ipv.pt
    
paths:
  '/utilizador':
    post:
      tags:
        - Utilizador
      summary: Registar utilizador
      description: Registar um novo utilizador
      consumes:
        - "application/json"
        - "application/xml"
      produces:
        - "application/json"
        - "application/xml"
      operationId: RegistarUtilizador
      parameters:
        - in: body
          name: utilizador_
          schema:
            type: object
            properties:
              cliente:
               type: string
               example: Janete Silva
      responses:
        201:
          description: Registo efetuado com sucesso!
          schema:
            type: object
            properties:
              cliente:
               type: string
               example: Janete Silva
        204:
          description: Erro sem conteúdo!
        226:
          description: Erro em uso!
        400:
          description: Requisição inválida!
        500:
          description: Erro interno no servidor!
        
          
          
          
          
          
          
          
          
          
          